### ISSUE TITLE
Document the most important ways to interact with this project (e.g. pointers to the clojure ecosystem)

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/g2-backend#1]

**Comment by mcbloch** [comment]
Ik heb de readme geupdate op de feat/intro_docs branch.
Heb je toevallig nog enige suggesties waar er info ontbreekt?

**Comment by wschella** [comment]
I had a wrong view about the goals and possibilities of Leiningen. So I guess documentation is sufficient. If anything I would add a small description of Leiningen in the readme, mentioning that it's an opinionated development tool basically managing your full project.

**Comment by mcbloch** [comment]
Leiningen is a bit like npm for javascript so I wouldn't say that it is opiniated. If it is, I wouldn't know on what...
I'll add the managing part.
