### ISSUE TITLE
Project screen

### ISSUE THREAD

**Issue by mcbloch** [ZeusWPI/g2-backend#14]
* List important files/docs
* Show latest activity?

* If linked to repository
  * List issues of repo
  * List branches of repo

Only be able to change state when logged in and authorized to edit.

* Keep in mind that nested projects will be added in the feature and that this will be a central thing in the ui.

**Comment by maartenvn** [comment]
Will the back-end provide the repository-linked information such as issues and branches or should the front-end do the API calls to github directly?

**Comment by mcbloch** [comment]
For now the plan is that the backend will provide all needed information. 

Otherwise only public repositories could be used because the front-end will not get the global access key to prevent miss-usage by the users.

**Comment by mcbloch** [comment]
Frontend will further be developed in it's own repository found here: https://github.com/ZeusWPI/g2-frontend/issues/2

Moving frontend issues there.
Closing.
